# Generated by Django 6.0.4 on 2026-05-27 12:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('style', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_bookable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('expected_finish_time', models.TimeField()),
                ('address', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending artist approval'), ('accepted', 'Accepted, deposit due'), ('deposit_paid', 'Deposit paid'), ('completed', 'Work completed, final payment due'), ('final_paid', 'Final paid'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('final_paid', models.BooleanField(default=False)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_appointments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.artistportfolio')),
            ],
            options={
                'ordering': ['-appointment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('booking', 'Booking'), ('like', 'Like'), ('review', 'Review'), ('private', 'Private message'), ('payment', 'Payment')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=240)),
                ('unread', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OccupiedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=240)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupied_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('artist', 'Makeup artist')], default='client', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('bio', models.TextField(blank=True)),
                ('preferred_styles', models.CharField(blank=True, max_length=240)),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('avatar_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('pause_start', models.TimeField(blank=True, null=True)),
                ('pause_end', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('artist', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
