# Generated by Django 6.0.4 on 2026-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistportfolio',
            name='availability_label',
            field=models.CharField(default='Available Sat-Sun', max_length=120),
        ),
        migrations.AddField(
            model_name='artistportfolio',
            name='card_size',
            field=models.CharField(choices=[('tall', 'Tall'), ('wide', 'Wide')], default='tall', max_length=10),
        ),
        migrations.AddField(
            model_name='artistportfolio',
            name='hot_score',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='artistportfolio',
            name='latest_score',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='artistportfolio',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artistportfolio',
            name='post_type',
            field=models.CharField(choices=[('bookable', 'Bookable'), ('request', 'Request'), ('tip', 'Tip')], default='bookable', max_length=20),
        ),
        migrations.AddField(
            model_name='artistportfolio',
            name='price_label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
