# Generated by Django 6.0.4 on 2026-05-29 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_messageitem_category_chatthread_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistportfolio',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='artistportfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='community_posts/'),
        ),
        migrations.AlterField(
            model_name='artistportfolio',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
